### PR TITLE
Composer phar file not necessary in the repository

### PR DESCRIPTION
**Pull request by zazoomauro**

### CODE REVIEW

**Comment by Codesleuth** [comment]
Hi @zazoomauro, would you mind elaborating on this PR?
If you believe `composer.phar` is not required, can you specify why? Since this failed the build, we can't accept this PR right now. Is there something we should change in the Travis build job for this to build successfully?

**Comment by zazoomauro** [comment]
Hi @Codesleuth,  Travis comes with an updated version of composer. Are you happy with this changes?

**Comment by zazoomauro** [comment]
Any update?

**Comment by Codesleuth** [comment]
Hey @zazoomauro, we've been considering this PR and testing it internally. I know there aren't any changes to functionality but the experience for other users who want to use the project from GitHub will change. We need to update the README to show how to run tests locally, but so far that's the only issue I can see with this PR.

We'll be reviewing it tomorrow, and I expect it to get merged.

Thanks again for taking the time to do this; we always appreciate community contributions and feedback for our SDKs :)

**Pull request merged**
